import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:wms_durich/core/theme/app_colors.dart';
import 'package:wms_durich/features/warehouse/data/models/buah_raw_models.dart';
import 'package:wms_durich/features/warehouse/data/models/lot_models.dart';
import 'package:wms_durich/features/warehouse/presentation/lot_in_process_page.dart';
import 'package:wms_durich/features/warehouse/presentation/providers/lot_provider.dart';

class AddLotStockProsesPage extends ConsumerStatefulWidget {
  final List<BuahRawItem> selectedBuahRaw;

  const AddLotStockProsesPage({
    super.key,
    required this.selectedBuahRaw,
  });

  @override
  ConsumerState<AddLotStockProsesPage> createState() =>
      _AddLotStockProsesPageState();
}

class _AddLotStockProsesPageState extends ConsumerState<AddLotStockProsesPage> {
  bool _isLotBaru = true;

  String? _selectedKondisi;
  String _autoGeneratedJenis = '';
  String _autoGeneratedJenisId = '';
  String? _kondisiError;

  String? _selectedLotExisting;
  String? _lotExistingError;

  final List<Map<String, String>> _kondisiOptions = [
    {'value': 'A', 'label': 'A - Bagus'},
    {'value': 'B', 'label': 'B - Rusak Sebagian / Bakal Pulping'},
    {'value': 'M', 'label': 'M - Belum Masak'},
    {'value': 'R', 'label': 'R - Reject / Rusak / Busuk'},
  ];

  bool _isSubmitting = false;
  bool _isSubmitted = false;
  String _createdLotId = '';
  String _createdLotKode = '';

  @override
  void initState() {
    super.initState();
    _initJenis();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _initDraftLotsFilter();
    });
  }

  void _initJenis() {
    final firstBuah = widget.selectedBuahRaw.first;
    _autoGeneratedJenis = firstBuah.jenisDurian.kode;
    _autoGeneratedJenisId = firstBuah.jenisDurian.id;
  }

  void _initDraftLotsFilter() {
    ref.read(draftLotsParamsProvider.notifier).setJenisDurianId(_autoGeneratedJenisId);
  }

  Future<void> _submitLot() async {
    _kondisiError = null;
    _lotExistingError = null;

    if (_isLotBaru) {
      if (_selectedKondisi == null) {
        setState(() {
          _kondisiError = 'Pilih kondisi buah';
        });
        return;
      }
    } else {
      if (_selectedLotExisting == null) {
        setState(() {
          _lotExistingError = 'Pilih lot tujuan';
        });
        return;
      }

      final draftLotsAsync = ref.read(draftLotsProvider);
      final draftLots = draftLotsAsync.value?.data ?? [];
      final selectedLot = draftLots.firstWhere(
        (lot) => lot.id == _selectedLotExisting,
      );

      if (selectedLot.jenisDurianNama != _autoGeneratedJenis) {
        _showJenisWarning(selectedLot.jenisDurianNama);
        return;
      }
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      final buahRawIds = widget.selectedBuahRaw.map((b) => b.id).toList();
      String lotId;

      if (_isLotBaru) {
        final createRequest = CreateLotRequest(
          jenisDurianId: _autoGeneratedJenisId,
          kondisiBuah: _selectedKondisi!,
        );

        final createResult = await ref
            .read(createLotControllerProvider.notifier)
            .createLot(createRequest);

        if (createResult == null) {
          _showErrorSnackbar('Gagal membuat lot baru');
          setState(() {
            _isSubmitting = false;
          });
          return;
        }

        lotId = createResult.id;
        _createdLotKode = createResult.kode;
      } else {
        lotId = _selectedLotExisting!;
        final draftLotsAsync = ref.read(draftLotsProvider);
        final draftLots = draftLotsAsync.value?.data ?? [];
        final selectedLot = draftLots.firstWhere((lot) => lot.id == lotId);
        _createdLotKode = selectedLot.kode;
      }

      final addItemsRequest = AddItemsToLotRequest(buahRawIds: buahRawIds);
      final addItemsResult = await ref
          .read(addItemsToLotControllerProvider.notifier)
          .addItems(lotId, addItemsRequest);

      if (addItemsResult == null) {
        _showErrorSnackbar('Gagal menambahkan buah ke lot');
        setState(() {
          _isSubmitting = false;
        });
        return;
      }

      setState(() {
        _createdLotId = lotId;
        _isSubmitted = true;
        _isSubmitting = false;
      });

      ref.invalidate(draftLotsProvider);

      _showSuccessSnackbar(
        _isLotBaru
            ? 'Lot baru $_createdLotKode berhasil dibuat dengan ${widget.selectedBuahRaw.length} buah'
            : '${widget.selectedBuahRaw.length} buah berhasil ditambahkan ke $_createdLotKode',
      );
    } catch (e) {
      setState(() {
        _isSubmitting = false;
      });
      _showErrorSnackbar('Terjadi kesalahan: $e');
    }
  }

  void _showSuccessSnackbar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.2),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                LucideIcons.checkCircle2,
                color: Colors.white,
                size: 20,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                message,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ),
          ],
        ),
        backgroundColor: AppColors.statusSuccessDark,
        behavior: SnackBarBehavior.floating,
        margin: const EdgeInsets.only(
          top: 80,
          left: 16,
          right: 16,
        ),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
        action: SnackBarAction(
          label: '✕',
          textColor: Colors.white,
          onPressed: () {
            ScaffoldMessenger.of(context).hideCurrentSnackBar();
          },
        ),
        duration: const Duration(seconds: 4),
      ),
    );
  }

  void _showErrorSnackbar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.2),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                LucideIcons.xCircle,
                color: Colors.white,
                size: 20,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                message,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ),
          ],
        ),
        backgroundColor: AppColors.statusDangerDark,
        behavior: SnackBarBehavior.floating,
        margin: const EdgeInsets.only(
          top: 80,
          left: 16,
          right: 16,
        ),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
        duration: const Duration(seconds: 4),
      ),
    );
  }

  void _showJenisWarning(String lotJenis) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          title: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: AppColors.orangeLight,
                  shape: BoxShape.circle,
                ),
                child: Icon(LucideIcons.alertTriangle,
                    color: AppColors.orangeDark, size: 24),
              ),
              const SizedBox(width: 12),
              const Expanded(
                child: Text(
                  'Jenis Tidak Cocok',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Lot yang dipilih memiliki jenis berbeda dengan buah yang akan ditambahkan:',
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.grey.shade800,
                ),
              ),
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: AppColors.orangeLight,
                  borderRadius: BorderRadius.circular(8),
                  border:
                      Border.all(color: AppColors.orangeDark.withOpacity(0.3)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(LucideIcons.package,
                            size: 16, color: AppColors.orangeDark),
                        const SizedBox(width: 8),
                        const Text(
                          'Jenis Lot Terpilih:',
                          style: TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(
                            color: AppColors.orangeDark,
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: Text(
                            lotJenis,
                            style: const TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Icon(LucideIcons.tag,
                            size: 16, color: AppColors.blueDark),
                        const SizedBox(width: 8),
                        const Text(
                          'Jenis Buah Dipilih:',
                          style: TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(
                            color: AppColors.blueDark,
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: Text(
                            _autoGeneratedJenis,
                            style: const TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Pastikan jenis lot dan buah yang dipilih sama.',
                style: TextStyle(
                  fontSize: 13,
                  color: Colors.grey.shade600,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              style: TextButton.styleFrom(
                padding:
                    const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                backgroundColor: AppColors.primary.withOpacity(0.1),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
              child: const Text(
                'Pilih Lot Lain',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
          actionsPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
        );
      },
    );
  }

  void _prosesLot() {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => const LotInProcessPage(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final draftLotsAsync = ref.watch(draftLotsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Lot Stock - Proses'),
        leading: IconButton(
          icon: const Icon(LucideIcons.arrowLeft),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.statusSuccessLight,
              border: Border(
                bottom: BorderSide(color: Colors.grey.shade300),
              ),
            ),
            child: Row(
              children: [
                Icon(LucideIcons.checkCircle,
                    color: AppColors.statusSuccessDark, size: 28),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Total Buah Dipilih',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.grey,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        '${widget.selectedBuahRaw.length} Buah',
                        style: const TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: AppColors.statusSuccessDark,
                        ),
                      ),
                    ],
                  ),
                ),
                if (_autoGeneratedJenis.isNotEmpty)
                  Flexible(
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 10, vertical: 5),
                      decoration: BoxDecoration(
                        color: AppColors.blueLight,
                        borderRadius: BorderRadius.circular(20),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(LucideIcons.tag,
                              size: 13, color: AppColors.blueDark),
                          const SizedBox(width: 4),
                          Flexible(
                            child: Text(
                              _autoGeneratedJenis,
                              style: const TextStyle(
                                color: AppColors.blueDark,
                                fontSize: 11,
                                fontWeight: FontWeight.w600,
                              ),
                              overflow: TextOverflow.ellipsis,
                              maxLines: 1,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
              ],
            ),
          ),
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: _buildToggleButton(
                          label: 'Lot Baru',
                          icon: LucideIcons.plus,
                          isActive: _isLotBaru,
                          onTap: () {
                            if (!_isSubmitted && !_isSubmitting) {
                              setState(() => _isLotBaru = true);
                            }
                          },
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _buildToggleButton(
                          label: 'Lot Sudah Ada',
                          icon: LucideIcons.package,
                          isActive: !_isLotBaru,
                          onTap: () {
                            if (!_isSubmitted && !_isSubmitting) {
                              setState(() => _isLotBaru = false);
                            }
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),
                  if (!_isSubmitted) ...[
                    if (_isLotBaru)
                      _buildLotBaruForm()
                    else
                      _buildLotExistingForm(draftLotsAsync),
                  ] else ...[
                    _buildSubmittedView(),
                  ],
                ],
              ),
            ),
          ),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 10,
                  offset: const Offset(0, -5),
                ),
              ],
            ),
            child: !_isSubmitted
                ? ElevatedButton(
                    onPressed: _isSubmitting ? null : _submitLot,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primary,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      elevation: 0,
                    ),
                    child: _isSubmitting
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor:
                                  AlwaysStoppedAnimation<Color>(Colors.white),
                            ),
                          )
                        : Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              const Icon(LucideIcons.check, size: 20),
                              const SizedBox(width: 8),
                              Text(
                                _isLotBaru ? 'Buat Lot Baru' : 'Tambahkan ke Lot',
                                style: const TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                  )
                : Row(
                    children: [
                      Expanded(
                        child: OutlinedButton(
                          onPressed: () => Navigator.pop(context),
                          style: OutlinedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            side: const BorderSide(color: AppColors.primary),
                          ),
                          child: const Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(LucideIcons.arrowLeft, size: 20),
                              SizedBox(width: 8),
                              Text(
                                'Kembali',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: ElevatedButton(
                          onPressed: _prosesLot,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.primary,
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            elevation: 0,
                          ),
                          child: const Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(LucideIcons.arrowRight, size: 20),
                              SizedBox(width: 8),
                              Text(
                                'Proses Lot',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
          ),
        ],
      ),
    );
  }

  Widget _buildToggleButton({
    required String label,
    required IconData icon,
    required bool isActive,
    required VoidCallback onTap,
  }) {
    return InkWell(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 12),
        decoration: BoxDecoration(
          color: isActive ? AppColors.primary : Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isActive ? AppColors.primary : Colors.grey.shade300,
            width: isActive ? 2 : 1,
          ),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              icon,
              size: 18,
              color: isActive ? Colors.white : Colors.grey.shade600,
            ),
            const SizedBox(width: 6),
            Flexible(
              child: Text(
                label,
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: isActive ? Colors.white : Colors.grey.shade600,
                ),
                overflow: TextOverflow.ellipsis,
                maxLines: 1,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLotBaruForm() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Kondisi (Grading)',
          style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        const SizedBox(height: 8),
        DropdownButtonFormField<String>(
          value: _selectedKondisi,
          decoration: InputDecoration(
            hintText: 'Pilih kondisi buah',
            hintStyle: const TextStyle(fontSize: 14),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: AppColors.primary, width: 2),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Colors.red),
            ),
            filled: true,
            fillColor: Colors.grey.shade50,
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            errorText: _kondisiError,
          ),
          isExpanded: true,
          items: _kondisiOptions.map((kondisi) {
            return DropdownMenuItem<String>(
              value: kondisi['value'],
              child: Text(
                kondisi['label']!,
                overflow: TextOverflow.ellipsis,
              ),
            );
          }).toList(),
          onChanged: (value) {
            setState(() {
              _selectedKondisi = value;
              _kondisiError = null;
            });
          },
        ),
        const SizedBox(height: 16),
        const Text(
          'Jenis',
          style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        const SizedBox(height: 8),
        TextFormField(
          initialValue: _autoGeneratedJenis,
          readOnly: true,
          decoration: InputDecoration(
            hintText: 'Auto-generated dari buah yang dipilih',
            hintStyle: const TextStyle(fontSize: 14),
            prefixIcon:
                const Icon(LucideIcons.tag, size: 20, color: Colors.grey),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            filled: true,
            fillColor: Colors.grey.shade100,
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
          ),
        ),
        const SizedBox(height: 16),
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.blueLight,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: AppColors.blueDark.withOpacity(0.3)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(LucideIcons.info, color: AppColors.blueDark, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'Lot baru akan dibuat dengan ${widget.selectedBuahRaw.length} buah jenis $_autoGeneratedJenis',
                  style: const TextStyle(
                    fontSize: 13,
                    color: AppColors.blueDark,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildLotExistingForm(AsyncValue<LotsResponse> draftLotsAsync) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Pilih Lot Tujuan',
          style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        const SizedBox(height: 8),
        draftLotsAsync.when(
          data: (response) {
            final draftLots = response.data;
            if (draftLots.isEmpty) {
              return Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.grey.shade100,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.grey.shade300),
                ),
                child: Row(
                  children: [
                    Icon(LucideIcons.packageX, color: Colors.grey.shade600),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        'Tidak ada lot DRAFT dengan jenis $_autoGeneratedJenis',
                        style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey.shade600,
                        ),
                      ),
                    ),
                  ],
                ),
              );
            }
            return DropdownButtonFormField<String>(
              value: _selectedLotExisting,
              decoration: InputDecoration(
                hintText: 'Pilih lot yang sudah ada',
                hintStyle: const TextStyle(fontSize: 14),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(color: Colors.grey.shade300),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(color: Colors.grey.shade300),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide:
                      const BorderSide(color: AppColors.primary, width: 2),
                ),
                errorBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: Colors.red),
                ),
                filled: true,
                fillColor: Colors.grey.shade50,
                contentPadding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                errorText: _lotExistingError,
              ),
              isExpanded: true,
              menuMaxHeight: 300,
              items: draftLots.map((lot) {
                return DropdownMenuItem<String>(
                  value: lot.id,
                  child: Text(
                    '${lot.kode} | ${lot.qtySisa} buah',
                    style: const TextStyle(fontSize: 14),
                    overflow: TextOverflow.ellipsis,
                  ),
                );
              }).toList(),
              onChanged: (value) {
                setState(() {
                  _selectedLotExisting = value;
                  _lotExistingError = null;
                });
              },
            );
          },
          loading: () => Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.grey.shade100,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.grey.shade300),
            ),
            child: const Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                SizedBox(
                  height: 20,
                  width: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
                SizedBox(width: 12),
                Text('Memuat daftar lot...'),
              ],
            ),
          ),
          error: (error, stack) => Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.statusDangerLight,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: AppColors.statusDangerDark),
            ),
            child: Row(
              children: [
                Icon(LucideIcons.alertCircle,
                    color: AppColors.statusDangerDark),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'Gagal memuat daftar lot: $error',
                    style: const TextStyle(
                      fontSize: 14,
                      color: AppColors.statusDangerDark,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(height: 16),
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.orangeLight,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: AppColors.orangeDark.withOpacity(0.3)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(LucideIcons.info, color: AppColors.orangeDark, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  '${widget.selectedBuahRaw.length} buah akan ditambahkan ke lot yang dipilih',
                  style: const TextStyle(
                    fontSize: 13,
                    color: AppColors.orangeDark,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildSubmittedView() {
    return Column(
      children: [
        Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: AppColors.statusSuccessLight,
            borderRadius: BorderRadius.circular(12),
            border:
                Border.all(color: AppColors.statusSuccessDark.withOpacity(0.3)),
          ),
          child: Column(
            children: [
              Icon(LucideIcons.checkCircle2,
                  color: AppColors.statusSuccessDark, size: 64),
              const SizedBox(height: 16),
              Text(
                _isLotBaru
                    ? 'Lot Berhasil Dibuat!'
                    : 'Buah Berhasil Ditambahkan!',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: AppColors.statusSuccessDark,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(
                      color: AppColors.statusSuccessDark.withOpacity(0.2)),
                ),
                child: Column(
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Kode Lot:',
                          style: TextStyle(
                            fontSize: 14,
                            color: Colors.grey,
                          ),
                        ),
                        Flexible(
                          child: Text(
                            _createdLotKode,
                            style: const TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                            ),
                            textAlign: TextAlign.end,
                          ),
                        ),
                      ],
                    ),
                    const Divider(height: 16),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Jumlah Buah:',
                          style: TextStyle(
                            fontSize: 14,
                            color: Colors.grey,
                          ),
                        ),
                        Text(
                          '${widget.selectedBuahRaw.length} buah',
                          style: const TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                    if (_isLotBaru) ...[
                      const Divider(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Jenis:',
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            _autoGeneratedJenis,
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                      const Divider(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Kondisi:',
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            _selectedKondisi ?? '-',
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        ),
        const SizedBox(height: 16),
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.blueLight,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: AppColors.blueDark.withOpacity(0.3)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(LucideIcons.info, color: AppColors.blueDark, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'Lot siap diproses ke tahap berikutnya atau kembali untuk menambah buah lainnya',
                  style: const TextStyle(
                    fontSize: 13,
                    color: AppColors.blueDark,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
