import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:wms_durich/core/theme/app_colors.dart';
import 'package:wms_durich/features/warehouse/presentation/add_lot_stock_page.dart';
import 'package:wms_durich/features/warehouse/presentation/lot_in_process_page.dart';

class AddLotStockProsesPage extends StatefulWidget {
  final List<BuahBelumSortir> selectedBuah;

  const AddLotStockProsesPage({
    super.key,
    required this.selectedBuah,
  });

  @override
  State<AddLotStockProsesPage> createState() => _AddLotStockProsesPageState();
}

class _AddLotStockProsesPageState extends State<AddLotStockProsesPage> {
  // State untuk tab yang dipilih
  bool _isLotBaru = true; // true = Lot Baru, false = Lot Sudah Ada

  // Form controllers dan state untuk Lot Baru
  String? _selectedKondisi;
  String _autoGeneratedJenis = '';
  String? _kondisiError;

  // Form controllers dan state untuk Lot Sudah Ada
  String? _selectedLotExisting;
  String? _lotExistingError;

  // Mock data kondisi (grading)
  final List<Map<String, String>> _kondisiOptions = [
    {'value': 'A', 'label': 'A - Bagus'},
    {'value': 'B', 'label': 'B - Rusak Sebagian / Bakal Pulping'},
    {'value': 'M', 'label': 'M - Belum Masak'},
    {'value': 'R', 'label': 'R - Reject / Rusak / Busuk'},
  ];

  // Mock data lot yang sudah ada (simulasi database)
  final List<Map<String, String>> _existingLots = [
    {'id': 'LOT-001', 'jenis': 'MK', 'kondisi': 'A', 'jumlah': '25'},
    {'id': 'LOT-002', 'jenis': 'BT', 'kondisi': 'B', 'jumlah': '18'},
    {'id': 'LOT-003', 'jenis': 'F0001', 'kondisi': 'A', 'jumlah': '30'},
    {'id': 'LOT-004', 'jenis': 'MK', 'kondisi': 'M', 'jumlah': '12'},
  ];

  // State untuk tracking submission
  bool _isSubmitted = false;
  String _createdLotId = '';

  @override
  void initState() {
    super.initState();
    _initJenis();
  }

  void _initJenis() {
    // Inisialisasi jenis dari buah yang dipilih
    // Karena sudah divalidasi di halaman sebelumnya, pasti jenis nya sama
    final jenisSet = widget.selectedBuah.map((b) => b.jenis).toSet();
    _autoGeneratedJenis = jenisSet.first;
  }

  void _submitLot() {
    // Reset errors
    _kondisiError = null;
    _lotExistingError = null;

    // Validasi berdasarkan tab yang dipilih
    if (_isLotBaru) {
      // Validasi Lot Baru
      if (_selectedKondisi == null) {
        setState(() {
          _kondisiError = 'Pilih kondisi buah';
        });
        return;
      }
    } else {
      // Validasi Lot Sudah Ada
      if (_selectedLotExisting == null) {
        setState(() {
          _lotExistingError = 'Pilih lot tujuan';
        });
        return;
      }

      // **VALIDASI: Cek jenis lot yang dipilih dengan jenis buah yang dipilih**
      final selectedLot = _existingLots.firstWhere(
        (lot) => lot['id'] == _selectedLotExisting,
      );
      final lotJenis = selectedLot['jenis']!;

      if (lotJenis != _autoGeneratedJenis) {
        // Jenis tidak cocok, tampilkan warning dan STOP di sini
        _showJenisWarning(lotJenis);
        return; // PENTING: Stop eksekusi, jangan lanjut ke setState dan snackbar
      }
    }

    // Jika validasi berhasil, proses submission
    setState(() {
      if (_isLotBaru) {
        // Generate LOT ID baru
        _createdLotId =
            'LOT-${DateTime.now().millisecondsSinceEpoch.toString().substring(7)}';
      } else {
        _createdLotId = _selectedLotExisting!;
      }

      _isSubmitted = true;
    });

    // Tampilkan custom snackbar sukses
    _showSuccessSnackbar(
      _isLotBaru
          ? 'Lot baru $_createdLotId berhasil dibuat dengan ${widget.selectedBuah.length} buah'
          : '${widget.selectedBuah.length} buah berhasil ditambahkan ke $_createdLotId',
    );
  }

  void _showSuccessSnackbar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.2),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                LucideIcons.checkCircle2,
                color: Colors.white,
                size: 20,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                message,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ),
          ],
        ),
        backgroundColor: AppColors.statusSuccessDark,
        behavior: SnackBarBehavior.floating,
        margin: const EdgeInsets.only(
          top: 80, // Posisi di bawah appbar (sekitar 80-100px dari atas)
          left: 16,
          right: 16,
        ),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
        action: SnackBarAction(
          label: '✕',
          textColor: Colors.white,
          onPressed: () {
            ScaffoldMessenger.of(context).hideCurrentSnackBar();
          },
        ),
        duration: const Duration(seconds: 4),
      ),
    );
  }

  void _showJenisWarning(String lotJenis) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          title: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: AppColors.orangeLight,
                  shape: BoxShape.circle,
                ),
                child: Icon(LucideIcons.alertTriangle,
                    color: AppColors.orangeDark, size: 24),
              ),
              const SizedBox(width: 12),
              const Expanded(
                child: Text(
                  'Jenis Tidak Cocok',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Lot yang dipilih memiliki jenis berbeda dengan buah yang akan ditambahkan:',
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.grey.shade800,
                ),
              ),
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: AppColors.orangeLight,
                  borderRadius: BorderRadius.circular(8),
                  border:
                      Border.all(color: AppColors.orangeDark.withOpacity(0.3)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(LucideIcons.package,
                            size: 16, color: AppColors.orangeDark),
                        const SizedBox(width: 8),
                        const Text(
                          'Jenis Lot Terpilih:',
                          style: TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(
                            color: AppColors.orangeDark,
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: Text(
                            lotJenis,
                            style: const TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Icon(LucideIcons.tag,
                            size: 16, color: AppColors.blueDark),
                        const SizedBox(width: 8),
                        const Text(
                          'Jenis Buah Dipilih:',
                          style: TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(
                            color: AppColors.blueDark,
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: Text(
                            _autoGeneratedJenis,
                            style: const TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Pastikan jenis lot dan buah yang dipilih sama.',
                style: TextStyle(
                  fontSize: 13,
                  color: Colors.grey.shade600,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              style: TextButton.styleFrom(
                padding:
                    const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                backgroundColor: AppColors.primary.withOpacity(0.1),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
              child: const Text(
                'Pilih Lot Lain',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
          actionsPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
        );
      },
    );
  }

  void _prosesLot() {
    // Navigate ke halaman Lot In-Process
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => const LotInProcessPage(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Lot Stock - Proses'),
        leading: IconButton(
          icon: const Icon(LucideIcons.arrowLeft),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Info Total Buah Dipilih
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.statusSuccessLight,
              border: Border(
                bottom: BorderSide(color: Colors.grey.shade300),
              ),
            ),
            child: Row(
              children: [
                Icon(LucideIcons.checkCircle,
                    color: AppColors.statusSuccessDark, size: 28),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Total Buah Dipilih',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.grey,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        '${widget.selectedBuah.length} Buah',
                        style: const TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: AppColors.statusSuccessDark,
                        ),
                      ),
                    ],
                  ),
                ),
                if (_autoGeneratedJenis.isNotEmpty)
                  Flexible(
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 10, vertical: 5),
                      decoration: BoxDecoration(
                        color: AppColors.blueLight,
                        borderRadius: BorderRadius.circular(20),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(LucideIcons.tag,
                              size: 13, color: AppColors.blueDark),
                          const SizedBox(width: 4),
                          Flexible(
                            child: Text(
                              _autoGeneratedJenis,
                              style: const TextStyle(
                                color: AppColors.blueDark,
                                fontSize: 11,
                                fontWeight: FontWeight.w600,
                              ),
                              overflow: TextOverflow.ellipsis,
                              maxLines: 1,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
              ],
            ),
          ),

          // Content
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Toggle Buttons: Lot Baru / Lot Sudah Ada
                  Row(
                    children: [
                      Expanded(
                        child: _buildToggleButton(
                          label: 'Lot Baru',
                          icon: LucideIcons.plus,
                          isActive: _isLotBaru,
                          onTap: () {
                            if (!_isSubmitted) {
                              setState(() => _isLotBaru = true);
                            }
                          },
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _buildToggleButton(
                          label: 'Lot Sudah Ada',
                          icon: LucideIcons.package,
                          isActive: !_isLotBaru,
                          onTap: () {
                            if (!_isSubmitted) {
                              setState(() => _isLotBaru = false);
                            }
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // Form Section
                  if (!_isSubmitted) ...[
                    if (_isLotBaru)
                      _buildLotBaruForm()
                    else
                      _buildLotExistingForm(),
                  ] else ...[
                    _buildSubmittedView(),
                  ],
                ],
              ),
            ),
          ),

          // Bottom Buttons
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 10,
                  offset: const Offset(0, -5),
                ),
              ],
            ),
            child: !_isSubmitted
                ? ElevatedButton(
                    onPressed: _submitLot,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primary,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      elevation: 0,
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(LucideIcons.check, size: 20),
                        const SizedBox(width: 8),
                        Text(
                          _isLotBaru ? 'Buat Lot Baru' : 'Tambahkan ke Lot',
                          style: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  )
                : Row(
                    children: [
                      Expanded(
                        child: OutlinedButton(
                          onPressed: () => Navigator.pop(context),
                          style: OutlinedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            side: const BorderSide(color: AppColors.primary),
                          ),
                          child: const Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(LucideIcons.arrowLeft, size: 20),
                              SizedBox(width: 8),
                              Text(
                                'Kembali',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: ElevatedButton(
                          onPressed: _prosesLot,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.primary,
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            elevation: 0,
                          ),
                          child: const Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(LucideIcons.arrowRight, size: 20),
                              SizedBox(width: 8),
                              Text(
                                'Proses Lot',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
          ),
        ],
      ),
    );
  }

  Widget _buildToggleButton({
    required String label,
    required IconData icon,
    required bool isActive,
    required VoidCallback onTap,
  }) {
    return InkWell(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 12),
        decoration: BoxDecoration(
          color: isActive ? AppColors.primary : Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isActive ? AppColors.primary : Colors.grey.shade300,
            width: isActive ? 2 : 1,
          ),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              icon,
              size: 18,
              color: isActive ? Colors.white : Colors.grey.shade600,
            ),
            const SizedBox(width: 6),
            Flexible(
              child: Text(
                label,
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: isActive ? Colors.white : Colors.grey.shade600,
                ),
                overflow: TextOverflow.ellipsis,
                maxLines: 1,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLotBaruForm() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Dropdown Kondisi
        const Text(
          'Kondisi (Grading)',
          style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        const SizedBox(height: 8),
        DropdownButtonFormField<String>(
          value: _selectedKondisi,
          decoration: InputDecoration(
            hintText: 'Pilih kondisi buah',
            hintStyle: const TextStyle(fontSize: 14),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: AppColors.primary, width: 2),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Colors.red),
            ),
            filled: true,
            fillColor: Colors.grey.shade50,
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            errorText: _kondisiError,
          ),
          isExpanded: true, // Penting: agar konten tidak overflow
          items: _kondisiOptions.map((kondisi) {
            return DropdownMenuItem<String>(
              value: kondisi['value'],
              child: Text(
                kondisi['label']!,
                overflow: TextOverflow.ellipsis,
              ),
            );
          }).toList(),
          onChanged: (value) {
            setState(() {
              _selectedKondisi = value;
              _kondisiError = null;
            });
          },
        ),
        const SizedBox(height: 16),

        // Input Jenis (Auto-generated, read-only)
        const Text(
          'Jenis',
          style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        const SizedBox(height: 8),
        TextFormField(
          initialValue: _autoGeneratedJenis,
          readOnly: true,
          decoration: InputDecoration(
            hintText: 'Auto-generated dari buah yang dipilih',
            hintStyle: const TextStyle(fontSize: 14),
            prefixIcon:
                const Icon(LucideIcons.tag, size: 20, color: Colors.grey),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            filled: true,
            fillColor: Colors.grey.shade100,
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
          ),
        ),
        const SizedBox(height: 16),

        // Info Box
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.blueLight,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: AppColors.blueDark.withOpacity(0.3)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(LucideIcons.info, color: AppColors.blueDark, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'Lot baru akan dibuat dengan ${widget.selectedBuah.length} buah jenis $_autoGeneratedJenis',
                  style: const TextStyle(
                    fontSize: 13,
                    color: AppColors.blueDark,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildLotExistingForm() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Dropdown Lot Yang Sudah Ada
        const Text(
          'Pilih Lot Tujuan',
          style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        const SizedBox(height: 8),
        DropdownButtonFormField<String>(
          value: _selectedLotExisting,
          decoration: InputDecoration(
            hintText: 'Pilih lot yang sudah ada',
            hintStyle: const TextStyle(fontSize: 14),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: AppColors.primary, width: 2),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Colors.red),
            ),
            filled: true,
            fillColor: Colors.grey.shade50,
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            errorText: _lotExistingError,
          ),
          isExpanded: true, // Penting: agar konten tidak overflow
          menuMaxHeight: 300, // Batasi tinggi menu dropdown
          items: _existingLots.map((lot) {
            return DropdownMenuItem<String>(
              value: lot['id'],
              child: Text(
                '${lot['id']} - Jenis: ${lot['jenis']} | Kondisi: ${lot['kondisi']} | ${lot['jumlah']} buah',
                style: const TextStyle(fontSize: 14),
                overflow: TextOverflow.ellipsis,
              ),
            );
          }).toList(),
          onChanged: (value) {
            setState(() {
              _selectedLotExisting = value;
              _lotExistingError = null;
            });
          },
        ),
        const SizedBox(height: 16),

        // Info Box
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.orangeLight,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: AppColors.orangeDark.withOpacity(0.3)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(LucideIcons.info, color: AppColors.orangeDark, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  '${widget.selectedBuah.length} buah akan ditambahkan ke lot yang dipilih',
                  style: const TextStyle(
                    fontSize: 13,
                    color: AppColors.orangeDark,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildSubmittedView() {
    return Column(
      children: [
        Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: AppColors.statusSuccessLight,
            borderRadius: BorderRadius.circular(12),
            border:
                Border.all(color: AppColors.statusSuccessDark.withOpacity(0.3)),
          ),
          child: Column(
            children: [
              Icon(LucideIcons.checkCircle2,
                  color: AppColors.statusSuccessDark, size: 64),
              const SizedBox(height: 16),
              Text(
                _isLotBaru
                    ? 'Lot Berhasil Dibuat!'
                    : 'Buah Berhasil Ditambahkan!',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: AppColors.statusSuccessDark,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(
                      color: AppColors.statusSuccessDark.withOpacity(0.2)),
                ),
                child: Column(
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'ID Lot:',
                          style: TextStyle(
                            fontSize: 14,
                            color: Colors.grey,
                          ),
                        ),
                        Text(
                          _createdLotId,
                          style: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    const Divider(height: 16),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Jumlah Buah:',
                          style: TextStyle(
                            fontSize: 14,
                            color: Colors.grey,
                          ),
                        ),
                        Text(
                          '${widget.selectedBuah.length} buah',
                          style: const TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                    if (_isLotBaru) ...[
                      const Divider(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Jenis:',
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            _autoGeneratedJenis,
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                      const Divider(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Kondisi:',
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            _selectedKondisi ?? '-',
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        ),
        const SizedBox(height: 16),

        // Info Box
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: AppColors.blueLight,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: AppColors.blueDark.withOpacity(0.3)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(LucideIcons.info, color: AppColors.blueDark, size: 20),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'Lot siap diproses ke tahap berikutnya atau kembali untuk menambah buah lainnya',
                  style: const TextStyle(
                    fontSize: 13,
                    color: AppColors.blueDark,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
